#! /usr/bin/env php
<?php
declare(strict_types=1);

class FileReader extends \SplFileObject {

  public function __construct(string $fname)
  {
     parent::__construct($fname, "r");

     $this->setFlags(\SplFileObject::READ_AHEAD | \SplFileObject::SKIP_EMPTY | \SplFileObject::DROP_NEW_LINE);
  }
}

/*
 After pandoc converts the .md to .html, if a table cell tag like '<td .....>' is not immediately followed by a <p> tag,
 then the cell contents are enclosed within beginning and ending parapgraph tags.

 For example:

    <td style="text-align: left;">die Frau</td>

 will become 

    <td style="text-align: left;"><p>die Frau</p></td>

 Comment:

 The regex assumes that the entire cell is in the $subject, it is on one line. The regex will fail if '</td>' is not on the line.
 However, table cells that are NOT followed by a <p> tag seems to fit on one line.
*/
function add_p_tag(string $subject)
{
  static $file_name_regex = '%^(<td(?>[^>]+)?>)(?!<p>)(.*)</td>%';

  static $replace = '$1<p>$2</p></td>';
  
  $result = preg_replace($file_name_regex, $replace, $subject);

  return $result;
}

/*
 * Calls add_a_tag() if a line starts with "<td"l
 */
function fix_td_tags(string $base_name)
{
   $html_name = $base_name . '.html';
   
   $infile  = new FileReader($html_name);
   
   $out_fname = $base_name . ".new"; 
   
   $outfile = new SplFileObject($out_fname, "w");

   foreach($infile as $line) {

      if (str_starts_with($line, "<td")) $line = add_p_tag($line);

      $outfile->fwrite($line . "\n"); 
   }

   // Move file-name.new to file-name.html
   $cmd = "mv $out_fname " . $html_name ;
   system( $cmd ); 

   echo "$html_name created.\n";
}

if ($argc < 2) {
   echo "Enter the start folder, optionally followed the regex the markdown file names must match.\n";
   return;
}
   
$start_dir = $argv[1]; // Get start dir 

$file_name_regex = isset($argv[2]) ?  $argv[2] : '.*'; // Get regex

$file_name_regex = "%$file_name_regex" . "%i";

$iter = new RecursiveIteratorIterator(  new RecursiveDirectoryIterator($start_dir) );

/*
 * The anonymous function ensures the file name matches the file_name_regex 
*/
$md_filter_iter = new \CallbackFilterIterator($iter, function(\SplFileInfo $info) use ($file_name_regex) { 
                                                    
                                                     return $info->isfile()  && (1 == preg_match($file_name_regex, $info->getfilename()) ) ? true : false;
                                                  });

/* 
 * Next we create a closure that calls pandoc to convert
 * the markdown files .md files to .html files using the
 * pandoc html template below.
 */
$template_name = '/usr/local/bin/pandoc-template';

$md2html = function(\SplFileInfo $info) use ($template_name) 
{
   $base_name = $info->getBasename('.md');

   $output = $base_name . '.html'; 
   
   $cmd =  'pandoc ' . $info->getPathname() . ' --template ' . $template_name . ' -t html --metadata title=$base_name -s -o ' . $output;
   
   echo "Command is: " . $cmd . "\n";

   system( $cmd );

   fix_td_tags($base_name);
};

$debug = 10;
/*
 * Finally, we invoke the cloosure $md2html on each file matching the regex.
 */
foreach ($md_filter_iter as $info) $md2html($info);

